# api-gateway/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: nyro-develop # Asegúrate que el namespace sea correcto
data:
  # General
  GATEWAY_LOG_LEVEL: "INFO" # O "DEBUG" para más detalle

  # URLs de los servicios downstream (usando nombres de Service de K8s)
  GATEWAY_INGEST_SERVICE_URL: "http://ingest-api-service.nyro-develop.svc.cluster.local:80"
  GATEWAY_QUERY_SERVICE_URL: "http://query-service.nyro-develop.svc.cluster.local:80"
  # GATEWAY_AUTH_SERVICE_URL: "http://auth-service.nyro-develop.svc.cluster.local:80" # Descomentar si se usa

  # --- VARIABLE AÑADIDA ---
  # URL del proyecto Supabase (la misma que usa el frontend)
  GATEWAY_SUPABASE_URL: "https://ymsilkrhstwxikjiqqog.supabase.co" # <-- ¡TU URL REAL DE SUPABASE!
  # ------------------------

  # --- VARIABLE AÑADIDA ---
  # Company ID por defecto a asignar si falta en el token
  # ¡REEMPLAZA con un UUID válido de una compañía existente en tu sistema!
  GATEWAY_DEFAULT_COMPANY_ID: "d7387dc8-0312-4b1c-97a5-f96f7995f36c"
  # ------------------------

  # HTTP Client settings (Ajustados según tu diff)
  GATEWAY_HTTP_CLIENT_TIMEOUT: "30"
  GATEWAY_HTTP_CLIENT_MAX_KEEPALIAS_CONNECTIONS: "100" # Nota: El nombre parece incorrecto en tu diff (KEEPALIAS vs KEEPALIVE)
  GATEWAY_HTTP_CLIENT_MAX_CONNECTIONS: "200"

  # JWT Algorithm (El Secret va en un objeto Secret)
  GATEWAY_JWT_ALGORITHM: "HS256"

  # Variables que estaban en el diff pero no directamente usadas por el gateway (podrían quitarse si no las necesitas aquí)
  GATEWAY_VERCEL_FRONTEND_URL: "https://atenex-frontend.vercel.app"
  # NGROK_URL: "https://tu-id.ngrok-free.app"