apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: nyro-develop
  labels:
    app: api-gateway
spec:
  replicas: 2 # Gateway suele beneficiarse de >1 réplica para disponibilidad
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          # La imagen será actualizada por el pipeline CI/CD
          image: ghcr.io/dev-nyro/api-gateway:latest # Placeholder, será reemplazado
          imagePullPolicy: Always # O IfNotPresent
          ports:
            - name: http # Nombre del puerto
              containerPort: 8080 # Puerto expuesto por el Dockerfile y Gunicorn
              protocol: TCP
          # Gunicorn command (no necesita especificarse si el CMD del Dockerfile es correcto)
          # El CMD del Dockerfile ya es: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:$(PORT)", "app.main:app"]
          # Podemos pasar el puerto vía env var si es necesario sobrescribir el default del Dockerfile
          env:
            - name: PORT
              value: "8080" # Asegura que Gunicorn use este puerto
          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: api-gateway-secrets
          resources: # Ajustar según necesidades
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health # Endpoint de health check
              port: http    # Nombre del puerto del contenedor
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      # imagePullSecrets: # Descomentar si usas registro privado
      # - name: ghcr-secret