apiVersion: v1
kind: Endpoints
metadata:
  name: reranker-gpu-service  
  namespace: nyro-develop
subsets:
- addresses:
  - ip: 192.168.65.3
  ports:
  - name: http             
    port: 8004             
    protocol: TCP