apiVersion: v1
kind: Service
metadata:
  name: reranker-gpu-service  
  namespace: nyro-develop
spec:
  ports:
  - name: http              
    protocol: TCP
    port: 80                
    targetPort: 8004        
  type: ClusterIP           