apiVersion: v1
kind: Service
metadata:
  name: reranker-gpu-service
  namespace: nyro-develop
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 80
      targetPort: 8004
