# reranker-gpu/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: reranker-gpu
  namespace: nyro-develop
spec:
  ports:
  - name: http
    port: 80          # Cluster-internal port
    targetPort: 8004  # Puerto real del contenedor en WSL2
  type: ClusterIP