apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: nyro-develop
  labels:
    app: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    app: postgresql
