apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: milvus
spec:
  components:
    dataNode:
      replicas: 1
    indexNode:
      replicas: 1
    proxy:
      replicas: 1
      serviceType: ClusterIP
    queryNode:
      replicas: 1
    mixCoord:
      replicas: 1
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          persistence:
            enabled: true
            size: 4Gi
    pulsar:
      inCluster:
        values:
          broker:
            replicaCount: 1
          zookeeper:
            replicaCount: 1
          bookkeeper:
            replicaCount: 1
    storage:
      external: true
      type: S3
      endpoint: minio-service.nyro-develop.svc.cluster.local:9000
      secretRef: minio-secret
  config:
    minio:
      bucketName: my-milvus-bucket
      rootPath: milvus/data
      useSSL: false
