# sparse-search-service/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sparse-search-index-builder
  namespace: nyro-develop
  labels:
    app: sparse-search-service
    component: index-builder
    app.kubernetes.io/name: sparse-search-index-builder
    app.kubernetes.io/part-of: atenex-platform
spec:
  schedule: "0 */6 * * *" 
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600 
      backoffLimit: 2 
      template:
        metadata:
          labels:
            app: sparse-search-service
            component: index-builder-pod
            app.kubernetes.io/name: sparse-search-index-builder-pod
        spec:
          # serviceAccountName: sparse-search-builder-sa # No se necesita si se usa la clave directamente
          volumes: # LLM: ADDED - Definir el volumen desde el Secret
            - name: gcs-key-volume
              secret:
                secretName: sparse-search-gcs-key # Nombre del Secret creado en K8s
          containers:
          - name: index-builder-container
            image: your-container-registry/sparse-search-service:v1.0.0 # Usa la misma imagen que el servicio
            imagePullPolicy: Always 
            command: ["python", "-m", "app.jobs.index_builder_cronjob"]
            args:
            - "--company-id"
            - "ALL" 
            envFrom:
            - configMapRef:
                name: sparse-search-service-config 
            - secretRef:
                name: sparse-search-service-secrets # Para SPARSE_POSTGRES_PASSWORD
            env:
            - name: SPARSE_POSTGRES_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: sparse-search-service-secrets 
                  key: SPARSE_POSTGRES_PASSWORD
            # LLM: ADDED - Configurar GOOGLE_APPLICATION_CREDENTIALS
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp-keys/key.json" # Ruta donde se montará la clave dentro del pod
            
            volumeMounts: # LLM: ADDED - Montar el volumen en el contenedor
              - name: gcs-key-volume
                mountPath: "/etc/gcp-keys" # Directorio donde se montará el contenido del Secret
                readOnly: true
            resources:
              requests:
                memory: "1Gi" 
                cpu: "500m"
              limits:
                memory: "4Gi" 
                cpu: "2" 
          restartPolicy: OnFailure 