# Ejemplo: query-service/kubernetes/configmap.yaml (o como se llame tu archivo)
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: nyro-develop
data:
  # General
  QUERY_LOG_LEVEL: "INFO" # O "DEBUG" para más detalle

  # PostgreSQL (Sin cambios)
  QUERY_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  QUERY_POSTGRES_PORT: "5432"
  QUERY_POSTGRES_USER: "postgres"
  QUERY_POSTGRES_DB: "atenex"
  # QUERY_POSTGRES_PASSWORD -> Proveniente de Secret

  # Milvus (Sin cambios)
  QUERY_MILVUS_URI: "http://milvus.nyro-develop.svc.cluster.local:19530"
  QUERY_MILVUS_COLLECTION_NAME: "document_chunks_minilm"
  QUERY_MILVUS_EMBEDDING_FIELD: "embedding"
  QUERY_MILVUS_CONTENT_FIELD: "content"
  QUERY_MILVUS_COMPANY_ID_FIELD: "company_id"
  QUERY_MILVUS_DOCUMENT_ID_FIELD: "document_id"
  QUERY_MILVUS_FILENAME_FIELD: "file_name"
  QUERY_MILVUS_GRPC_TIMEOUT: "15"
  # QUERY_MILVUS_METADATA_FIELDS: (...) # Se usarán los defaults de config.py si no se especifica

  # Embedding Settings (FastEmbed - Sin cambios)
  QUERY_FASTEMBED_MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
  QUERY_EMBEDDING_DIMENSION: "384"
  QUERY_FASTEMBED_QUERY_PREFIX: "query: "

  # Gemini LLM Settings
  # --- LLM_CORRECTION: Set correct model name ---
  QUERY_GEMINI_MODEL_NAME: "gemini-2.5-flash-preview-04-17"
  # QUERY_GEMINI_API_KEY -> Proveniente de Secret

  # RAG Pipeline Control & Parameters
  # --- LLM_CORRECTION: Increase K and set new context limit ---
  QUERY_RETRIEVER_TOP_K: "100" # K inicial para cada retriever (aumentado)
  QUERY_MAX_CONTEXT_CHUNKS: "75" # Máximo de chunks para el prompt del LLM (aumentado)
  QUERY_MAX_PROMPT_TOKENS: "500000" # Límite de tokens (opcional, informativo)

  QUERY_BM25_ENABLED: "true" # Habilitar BM25 por defecto
  QUERY_RERANKER_ENABLED: "true" # Habilitar Reranker por defecto
  QUERY_RERANKER_MODEL_NAME: "BAAI/bge-reranker-base" # Modelo reranker (sin cambios)
  QUERY_DIVERSITY_FILTER_ENABLED: "false" # MANTENER DESHABILITADO para maximizar contexto fácilmente
  # QUERY_DIVERSITY_LAMBDA: "0.5" # Irrelevante si DIVERSITY_FILTER_ENABLED es false
  # QUERY_HYBRID_FUSION_ALPHA: "0.5" # (Actualmente no usado por RRF)

  # Prompt Templates (Sin cambios aquí, usan los defaults de config.py)
  # QUERY_RAG_PROMPT_TEMPLATE: |
  #   ...
  # QUERY_GENERAL_PROMPT_TEMPLATE: |
  #   ...