apiVersion: v1
kind: ConfigMap
metadata:
  # --- Asume un nombre distinto para el query-service ---
  name: query-service-config
  namespace: nyro-develop
data:
  # General
  QUERY_LOG_LEVEL: "INFO"

  # PostgreSQL (Mismos datos que ingest)
  QUERY_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  QUERY_POSTGRES_PORT: "5432"
  QUERY_POSTGRES_USER: "postgres"
  QUERY_POSTGRES_DB: "atenex"
  # QUERY_POSTGRES_PASSWORD -> Secret

  # Milvus (Mismos datos que ingest, pero con campos explícitos)
  QUERY_MILVUS_URI: "http://milvus-standalone.nyro-develop.svc.cluster.local:19530"
  QUERY_MILVUS_COLLECTION_NAME: "document_chunks_haystack" # Debe coincidir con ingest
  # --- Campos explícitos para Milvus ---
  QUERY_MILVUS_EMBEDDING_FIELD: "embedding" # Coincide con ingest
  QUERY_MILVUS_CONTENT_FIELD: "content"     # Coincide con ingest
  QUERY_MILVUS_COMPANY_ID_FIELD: "company_id" # Coincide con ingest
  # ---------------------------------------

  # Embedding Settings (FastEmbed)
  # --- CORRECTION: Alineado con ingest-service ---
  QUERY_FASTEMBED_MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
  QUERY_EMBEDDING_DIMENSION: "384" # Dimensión correcta para MiniLM
  QUERY_FASTEMBED_QUERY_PREFIX: "query: "
  # -------------------------------------------

  # Gemini LLM Settings
  QUERY_GEMINI_MODEL_NAME: "gemini-1.5-flash-latest"
  # QUERY_GEMINI_API_KEY -> Secret

  # RAG Settings
  QUERY_RETRIEVER_TOP_K: "5"
  # Los templates largos se dejan en el código por defecto, se pueden externalizar si es necesario.