# k8s/query-service-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: nyro-develop
data:
  QUERY_LOG_LEVEL: "INFO"

  # PostgreSQL Interno
  QUERY_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  QUERY_POSTGRES_PORT: "5432"
  QUERY_POSTGRES_USER: "postgres"
  QUERY_POSTGRES_DB: "atenex"

  # --- Milvus ---
  # *** CORREGIDO: Apunta al servicio en namespace 'default' ***
  QUERY_MILVUS_URI: "http://milvus-milvus.default.svc.cluster.local:19530"
  QUERY_MILVUS_COLLECTION_NAME: "document_chunks_haystack" # Nombre de tu colección
  QUERY_MILVUS_COMPANY_ID_FIELD: "company_id" # Campo para filtrar por tenant

  # OpenAI Embedding
  QUERY_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  QUERY_EMBEDDING_DIMENSION: "1536" # Verificado en config.py

  # Gemini LLM
  QUERY_GEMINI_MODEL_NAME: "gemini-1.5-flash-latest"

  # RAG Pipeline
  QUERY_RETRIEVER_TOP_K: "5"
  # QUERY_RAG_PROMPT_TEMPLATE: "" # Usa default

  # Service Client Config
  QUERY_HTTP_CLIENT_TIMEOUT: "60"
  QUERY_HTTP_CLIENT_MAX_RETRIES: "2"
  QUERY_HTTP_CLIENT_BACKOFF_FACTOR: "1.0"