apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: nyro-develop
data:
  # General
  QUERY_LOG_LEVEL: "INFO"

  # PostgreSQL
  QUERY_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  QUERY_POSTGRES_PORT: "5432"
  QUERY_POSTGRES_USER: "postgres"
  QUERY_POSTGRES_DB: "atenex"
  # QUERY_POSTGRES_PASSWORD -> Proveniente de Secret

  # Milvus/Zilliz
  QUERY_MILVUS_URI: "https://in03-0afab716eb46d7f.serverless.gcp-us-west1.cloud.zilliz.com" # MODIFIED
  QUERY_MILVUS_COLLECTION_NAME: "document_chunks_minilm"
  QUERY_MILVUS_EMBEDDING_FIELD: "embedding"
  QUERY_MILVUS_CONTENT_FIELD: "content"
  QUERY_MILVUS_COMPANY_ID_FIELD: "company_id"
  QUERY_MILVUS_DOCUMENT_ID_FIELD: "document_id"
  QUERY_MILVUS_FILENAME_FIELD: "file_name"
  QUERY_MILVUS_GRPC_TIMEOUT: "20" # Increased timeout as per consideration for Zilliz Cloud
  # QUERY_MILVUS_METADATA_FIELDS: (...) # Uses default from config.py

  # Embedding Settings
  QUERY_EMBEDDING_DIMENSION: "384"
  QUERY_EMBEDDING_SERVICE_URL: "http://embedding-service.nyro-develop.svc.cluster.local:80/api/v1/embed" # Corrected path if client expects full path


  # Gemini LLM Settings
  QUERY_GEMINI_MODEL_NAME: "gemini-1.5-flash-latest"
  # QUERY_GEMINI_API_KEY -> Proveniente de Secret

  # RAG Pipeline Control & Parameters
  QUERY_RETRIEVER_TOP_K: "100"
  QUERY_MAX_CONTEXT_CHUNKS: "75"
  QUERY_MAX_PROMPT_TOKENS: "500000" # Ensure this is appropriate for Gemini Flash

  QUERY_BM25_ENABLED: "true"
  QUERY_RERANKER_ENABLED: "true"
  # QUERY_RERANKER_MODEL_NAME: "BAAI/bge-reranker-base" # Model name is now handled by reranker-service
  QUERY_RERANKER_SERVICE_URL: "http://reranker-service.nyro-develop.svc.cluster.local:80" # URL for reranker-service
  QUERY_DIVERSITY_FILTER_ENABLED: "true"
  QUERY_DIVERSITY_LAMBDA: "0.5"

  # HTTP Client Settings for external services (embedding, reranker)
  QUERY_EMBEDDING_CLIENT_TIMEOUT: "30"
  QUERY_RERANKER_CLIENT_TIMEOUT: "30"
  QUERY_HTTP_CLIENT_TIMEOUT: "60" # General default if not overridden
  QUERY_HTTP_CLIENT_MAX_RETRIES: "2"
  QUERY_HTTP_CLIENT_BACKOFF_FACTOR: "1.0"

  # Chat history settings
  QUERY_MAX_CHAT_HISTORY_MESSAGES: "10"
  QUERY_NUM_SOURCES_TO_SHOW: "7"