apiVersion: v1
kind: ConfigMap
metadata:
  name: query-service-config
  namespace: nyro-develop # Asegúrate que el namespace es correcto
data:
  # General
  QUERY_LOG_LEVEL: "INFO" # O "DEBUG" para más detalle

  # --- Configuración PostgreSQL INTERNA ---
  QUERY_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local" # Parece correcto ahora
  QUERY_POSTGRES_PORT: "5432"
  QUERY_POSTGRES_USER: "postgres"
  QUERY_POSTGRES_DB: "atenex" # Confirmado
  # QUERY_POSTGRES_PASSWORD se define en el Secret 'query-service-secrets'
  # ----------------------------------------

  # --- CORRECCIÓN: Apuntar al nombre de servicio correcto de Milvus ---
  QUERY_MILVUS_URI: "http://milvus-milvus.default.svc.cluster.local:19530" # <-- CORREGIDO (milvus-milvus en namespace default según kubectl)
  QUERY_MILVUS_COLLECTION_NAME: "document_chunks_haystack"
  # QUITAR argumentos no usados por milvus-haystack 2.x:
  # QUERY_MILVUS_EMBEDDING_FIELD: "embedding" # Eliminado
  # QUERY_MILVUS_CONTENT_FIELD: "content"     # Eliminado
  QUERY_MILVUS_COMPANY_ID_FIELD: "company_id" # Mantener si lo usas en filtros Haystack

  # OpenAI Embedding (Sin cambios)
  QUERY_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  QUERY_EMBEDDING_DIMENSION: "1536"
  # QUERY_OPENAI_API_KEY va en Secrets

  # Gemini LLM (Sin cambios)
  QUERY_GEMINI_MODEL_NAME: "gemini-1.5-flash-latest"
  # QUERY_GEMINI_API_KEY va en Secrets

  # RAG Pipeline (Sin cambios)
  QUERY_RETRIEVER_TOP_K: "5"
  # QUERY_RAG_PROMPT_TEMPLATE: # Usará el default de config.py si no se define aquí

  # Service Client Config (Sin cambios)
  QUERY_HTTP_CLIENT_TIMEOUT: "60"
  QUERY_HTTP_CLIENT_MAX_RETRIES: "2"
  QUERY_HTTP_CLIENT_BACKOFF_FACTOR: "1.0"