# query-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-deployment
  namespace: nyro-develop
  labels:
    app: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service # Nombre del contenedor
          # La imagen será actualizada por el pipeline CI/CD
          image: ghcr.io/dev-nyro/query-service:develop-d26f90b
          imagePullPolicy: Always # O IfNotPresent
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          command: ["gunicorn"]
          args: [
              "-k", "uvicorn.workers.UvicornWorker",
              # *** CORRECCIÓN: Reducir número de workers ***
              "-w", "2",             # Reducido de 4 a 2 para aliviar carga inicial
              "-b", "0.0.0.0:8001",
              "-t", "120",
              "app.main:app"
            ]
          envFrom:
            - configMapRef:
                name: query-service-config
            - secretRef:
                name: query-service-secrets
          resources: # Mantener los recursos aumentados de la iteración anterior
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1500m"
              memory: "2Gi"
          readinessProbe: # Mantener probes ajustados
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 15
            failureThreshold: 5
            successThreshold: 1
          livenessProbe: # Mantener probes ajustados
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
            successThreshold: 1
      # imagePullSecrets:
      # - name: ghcr-secret