# query-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service-deployment
  namespace: nyro-develop # Asegurar namespace correcto
  labels:
    app: query-service
spec:
  replicas: 1 # Empezar con 1, escalar según necesidad
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
        - name: query-service # Nombre del contenedor
          # La imagen será actualizada por el pipeline CI/CD (este es un placeholder)
          image: ghcr.io/dev-nyro/query-service:develop-23382da
          imagePullPolicy: Always # O IfNotPresent si prefieres usar caché local en dev
          ports:
            - name: http
              containerPort: 8001 # Puerto interno definido en Dockerfile/Config
              protocol: TCP
          # Comando Gunicorn ajustado
          command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker"]
          args: [
              "-w", "2", # Número de workers (ajustar según CPU/Memoria)
              "-b", "0.0.0.0:8001", # Vincular al puerto interno
              "-t", "120", # Worker timeout
              # "--log-level", "$(QUERY_LOG_LEVEL)", # Heredar nivel de log (opcional)
              "app.main:app"
            ]
          envFrom:
            - configMapRef:
                name: query-service-config
            - secretRef:
                name: query-service-secrets # Asegurar que el Secret existe
          resources: # Aumentado para mejorar velocidad de arranque y performance
            requests:
              cpu: "1500m" # 1.5 vCPU
              memory: "3Gi"
            limits:
              cpu: "3000m" # 3 vCPU
              memory: "8Gi"

          # --- Sondas eliminadas según solicitud ---
          # livenessProbe: ...
          # readinessProbe: ...

      # Descomentar si se usa registro privado
      # imagePullSecrets:
      # - name: your-registry-secret