apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedding-service-deployment
  namespace: nyro-develop
  labels:
    app: embedding-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedding-service
  template:
    metadata:
      labels:
        app: embedding-service
    spec:
      volumes:
        - name: dshm # Nombre del volumen
          emptyDir:
            medium: Memory # Usar memoria para este emptyDir
            sizeLimit: 256Mi # Límite de tamaño para el tmpfs
      containers:
        - name: embedding-service
          image: ghcr.io/dev-nyro/embedding-service:develop-d60bccd
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8003
              protocol: TCP
          envFrom:
            - configMapRef:
                name: embedding-service-config
          volumeMounts:
            - name: dshm # Referencia al volumen definido arriba
              mountPath: /dev/shm # CORREGIDO: Montar en /dev/shm
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1500m"
              memory: "3Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30 # Dar tiempo suficiente para la descarga y carga del modelo
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            # livenessProbe: # ELIMINADO según solicitud
            #   httpGet:
            #     path: /health
            #     port: http
            #   initialDelaySeconds: 60
            #   periodSeconds: 15
            #   timeoutSeconds: 5
            #   failureThreshold: 3
