#ingest-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO"

  # Celery
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/1"

  # PostgreSQL
  INGEST_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  INGEST_POSTGRES_PORT: "5432"
  INGEST_POSTGRES_USER: "postgres"
  INGEST_POSTGRES_DB: "atenex"
  # INGEST_POSTGRES_PASSWORD -> Secret

  # Milvus
  INGEST_MILVUS_URI: "http://milvus-standalone.nyro-develop.svc.cluster.local:19530" # Nombre de servicio actualizado
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_minilm"
  INGEST_MILVUS_GRPC_TIMEOUT: "10"

  # Google Cloud Storage
  INGEST_GCS_BUCKET_NAME: "atenex"

  # Embedding Settings
  # INGEST_EMBEDDING_MODEL_ID: "sentence-transformers/all-MiniLM-L6-v2" # Eliminado
  INGEST_EMBEDDING_DIMENSION: "384" # Mantenido para el esquema de Milvus

  # Tokenizer Settings
  INGEST_TIKTOKEN_ENCODING_NAME: "cl100k_base"

  # URLs for dependent services
  INGEST_EMBEDDING_SERVICE_URL: "http://embedding-service.nyro-develop.svc.cluster.local:8003/api/v1/embed"
  INGEST_DOCPROC_SERVICE_URL: "http://docproc-service.nyro-develop.svc.cluster.local:8005/api/v1/process"

  # Splitter Settings - Eliminados
  # INGEST_SPLITTER_CHUNK_SIZE: "1000"
  # INGEST_SPLITTER_CHUNK_OVERLAP: "250"