# configmap.yaml (CORREGIDO)
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO"

  # Celery (using K8s service names)
  INGEST_CELERY_BROKER_URL: "redis://redis-service.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service.nyro-develop.svc.cluster.local:6379/1"

  # Database (Supabase Direct Connection - NO placeholders, NO secrets here)
  # *** CORREGIDO: Apuntar al host EXTERNO de Supabase ***
  INGEST_POSTGRES_SERVER: "db.ymsilkrhstwxikjiqqog.supabase.co" # Host de tu proyecto Supabase
  INGEST_POSTGRES_PORT: "5432"  # Puerto estándar de conexión directa
  INGEST_POSTGRES_USER: "postgres" # Usuario estándar de Supabase (o el específico si cambiaste)
  INGEST_POSTGRES_DB: "postgres"   # Base de datos estándar de Supabase (o la específica)

  # Milvus (using K8s service name)
  INGEST_MILVUS_URI: "http://milvus-service.nyro-develop.svc.cluster.local:19530"
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_haystack"

  # MinIO (using K8s service name)
  INGEST_MINIO_ENDPOINT: "minio-service.nyro-develop.svc.cluster.local:9000"
  INGEST_MINIO_BUCKET_NAME: "ingested-documents"
  # *** CORREGIDO (Estilo): Usar booleano YAML ***
  INGEST_MINIO_USE_SECURE: "false" # YAML boolean false

  # Haystack/OpenAI
  INGEST_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  # INGEST_EMBEDDING_DIMENSION is now set automatically by the validator in config.py based on the model
  # INGEST_EMBEDDING_DIMENSION: "1536" # Can be removed if validator handles it
  INGEST_SPLITTER_CHUNK_SIZE: "500"
  INGEST_SPLITTER_CHUNK_OVERLAP: "50"
  INGEST_SPLITTER_SPLIT_BY: "word"

  # Add other non-sensitive settings if needed
  # INGEST_PROJECT_NAME: "Ingest Service Prod" # Example override