apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO" # O "DEBUG" para más detalle

  # Celery
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/1"

  # PostgreSQL
  INGEST_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  INGEST_POSTGRES_PORT: "5432"
  INGEST_POSTGRES_USER: "postgres"
  INGEST_POSTGRES_DB: "atenex"
  # INGEST_POSTGRES_PASSWORD -> Secret

  # Milvus
  INGEST_MILVUS_URI: "http://milvus-standalone.nyro-develop.svc.cluster.local:19530"
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_haystack" # Nombre de la colección (ajusta si es necesario)
  INGEST_MILVUS_GRPC_TIMEOUT: "10" # Timeout en segundos

  # --- MinIO Variables REMOVED ---
  # INGEST_MINIO_ENDPOINT: "minio-service.nyro-develop.svc.cluster.local:9000"
  # INGEST_MINIO_BUCKET_NAME: "ingested-documents"
  # INGEST_MINIO_USE_SECURE: "false"
  # INGEST_MINIO_ACCESS_KEY / SECRET_KEY -> Secret

  # --- Google Cloud Storage Added ---
  INGEST_GCS_BUCKET_NAME: "atenex" # Nombre del bucket en GCS

  # Embedding Settings (using SentenceTransformers)
  # --- CORRECTION: Adjusted dimension to match BAAI/bge-large model ---
  # --- Verify this is the intended model and dimension. ---
  # --- If using all-MiniLM-L6-v2, change MODEL to that and DIMENSION to 384 ---
  INGEST_EMBEDDING_MODEL_ID: "sentence-transformers/all-MiniLM-L6-v2"
  INGEST_EMBEDDING_DIMENSION: "384" # Dimension for MiniLM-L6-v2
  # --------------------------------------------------------------------
  # INGEST_FASTEMBED_MODEL: "BAAI/bge-large-en-v1.5" # Replaced by EMBEDDING_MODEL_ID
  INGEST_USE_GPU: "false" # Kept, but likely unused for SentenceTransformers CPU

  # Splitter Settings
  INGEST_SPLITTER_CHUNK_SIZE: "1000"
  INGEST_SPLITTER_CHUNK_OVERLAP: "250"
  # INGEST_SPLITTER_SPLIT_BY: "word" # Removed - Not used by current splitter