# ingest-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO" # O "DEBUG"

  # Celery (Sin cambios aquí, sigue apuntando a Redis interno)
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/1"

  # Database (Supabase Session Pooler Connection)
  # *** CORREGIDO: Puerto cambiado a 6543 ***
  INGEST_POSTGRES_SERVER: "aws-0-sa-east-1.pooler.supabase.com" # Host del Session Pooler
  INGEST_POSTGRES_PORT: "6543"                                  # Puerto del Session Pooler (CORREGIDO)
  INGEST_POSTGRES_USER: "postgres.ymsilkrhstwxikjiqqog"         # Usuario del Session Pooler (postgres.<project-ref>)
  INGEST_POSTGRES_DB: "postgres"                               # Base de datos (generalmente 'postgres')
  # INGEST_POSTGRES_PASSWORD se gestiona a través de Secrets

  # Milvus (Sin cambios aquí)
  INGEST_MILVUS_URI: "http://milvus-service.nyro-develop.svc.cluster.local:19530"
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_haystack"

  # MinIO (Sin cambios aquí)
  INGEST_MINIO_ENDPOINT: "minio-service.nyro-develop.svc.cluster.local:9000"
  INGEST_MINIO_BUCKET_NAME: "ingested-documents"
  INGEST_MINIO_USE_SECURE: "false"
  # INGEST_MINIO_ACCESS_KEY y INGEST_MINIO_SECRET_KEY se gestionan via Secrets

  # Haystack/OpenAI (Sin cambios aquí)
  INGEST_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  # INGEST_OPENAI_API_KEY se gestiona via Secrets
  INGEST_SPLITTER_CHUNK_SIZE: "500"
  INGEST_SPLITTER_CHUNK_OVERLAP: "50"
  INGEST_SPLITTER_SPLIT_BY: "word"

  # Add other non-sensitive settings if needed