# ingest-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO" # O "DEBUG"

  # Celery (Sin cambios)
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/1"

  # --- Configuración PostgreSQL INTERNA ---
  INGEST_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  INGEST_POSTGRES_PORT: "5432"
  INGEST_POSTGRES_USER: "postgres"
  INGEST_POSTGRES_DB: "atenex"
  # INGEST_POSTGRES_PASSWORD se define en el Secret 'ingest-service-secrets'
  # ----------------------------------------

  # Milvus (Sin cambios)
  INGEST_MILVUS_URI: "http://milvus-service.nyro-develop.svc.cluster.local:19530" # Asumiendo que Milvus está en nyro-develop ahora también
  # O si sigue en default: "http://milvus-milvus.default.svc.cluster.local:19530"
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_haystack" # Mantén tu nombre de colección

  # MinIO (Sin cambios)
  INGEST_MINIO_ENDPOINT: "minio-service.nyro-develop.svc.cluster.local:9000"
  INGEST_MINIO_BUCKET_NAME: "ingested-documents" # Mantén tu nombre de bucket
  INGEST_MINIO_USE_SECURE: "false"
  # INGEST_MINIO_ACCESS_KEY y INGEST_MINIO_SECRET_KEY se gestionan via Secrets

  # Haystack/OpenAI (Sin cambios)
  INGEST_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  # INGEST_OPENAI_API_KEY se gestiona via Secrets
  INGEST_SPLITTER_CHUNK_SIZE: "500"
  INGEST_SPLITTER_CHUNK_OVERLAP: "50"
  INGEST_SPLITTER_SPLIT_BY: "word"

  # Otros parámetros de Haystack/Milvus (Asegúrate que estos son correctos)
  # INGEST_MILVUS_INDEX_PARAMS: '{"metric_type": "COSINE", "index_type": "HNSW", "params": {"M": 16, "efConstruction": 256}}'
  # INGEST_MILVUS_SEARCH_PARAMS: '{"metric_type": "COSINE", "params": {"ef": 128}}'