# ingest-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingest-service-config
  namespace: nyro-develop
data:
  # General
  INGEST_LOG_LEVEL: "INFO" # O "DEBUG" para más detalle

  # Celery
  INGEST_CELERY_BROKER_URL: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/0"
  INGEST_CELERY_RESULT_BACKEND: "redis://redis-service-master.nyro-develop.svc.cluster.local:6379/1"

  # PostgreSQL
  INGEST_POSTGRES_SERVER: "postgresql-service.nyro-develop.svc.cluster.local"
  INGEST_POSTGRES_PORT: "5432"
  INGEST_POSTGRES_USER: "postgres"
  INGEST_POSTGRES_DB: "atenex"
  # INGEST_POSTGRES_PASSWORD -> Secret

  # Milvus
  INGEST_MILVUS_URI: "http://milvus-milvus.default.svc.cluster.local:19530"
  INGEST_MILVUS_COLLECTION_NAME: "document_chunks_haystack"

  # MinIO
  INGEST_MINIO_ENDPOINT: "minio-service.nyro-develop.svc.cluster.local:9000"
  INGEST_MINIO_BUCKET_NAME: "ingested-documents"
  INGEST_MINIO_USE_SECURE: "false"
  # INGEST_MINIO_ACCESS_KEY / SECRET_KEY -> Secret

  # --- CORREGIDO: Settings para FastEmbed en CPU ---
  # Ya no se usa para embeddings de ingesta
  # INGEST_OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
  # INGEST_OPENAI_API_KEY -> Secret (Mantener solo si se usa en OTRO lugar)

  # FastEmbed Settings
  INGEST_FASTEMBED_MODEL: "BAAI/bge-large-en-v1.5" # Modelo local a usar
  INGEST_USE_GPU: "false"                        # Desactivar uso de GPU
  # Dimensión correcta para BAAI/bge-large-en-v1.5
  INGEST_EMBEDDING_DIMENSION: "1024"

  # Splitter Settings (sin cambios)
  INGEST_SPLITTER_CHUNK_SIZE: "500"
  INGEST_SPLITTER_CHUNK_OVERLAP: "50"
  INGEST_SPLITTER_SPLIT_BY: "word"