# ingest-service/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker-deployment
  namespace: nyro-develop
  labels:
    app: ingest-worker
spec:
  replicas: 1 # Puedes aumentar a 2 o más si una sola CPU/GPU no es suficiente para la carga
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
    spec:
      # --- Comentario GPU ---
      # Para usar GPU (ej. tu RTX 4060), necesitas:
      # 1. Nodos con GPU y drivers NVIDIA + NVIDIA Container Toolkit instalados.
      # 2. El Dockerfile debe incluir PyTorch+CUDA y las dependencias necesarias.
      # 3. Descomentar y ajustar la sección 'resources' abajo para solicitar GPUs.
      # 4. Cambiar OpenAIDocumentEmbedder por un embedder local compatible con GPU en process_document.py.
      # 5. Posiblemente añadir nodeSelector o tolerations si los nodos GPU están etiquetados/taintados.
      # Ejemplo nodeSelector (si tus nodos GPU tienen esta etiqueta):
      # nodeSelector:
      #   gpu-type: "nvidia-rtx-4060" # O la etiqueta que uses
      # ---------------------
      containers:
        - name: ingest-worker
          # Asegúrate que la imagen es la correcta y está actualizada
          image: ghcr.io/dev-nyro/ingest-service:develop-b148a17
          imagePullPolicy: Always # O IfNotPresent
          # ***** CONCURRENCIA AUMENTADA *****
          command: ["celery"]
          args: ["-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "-P", "gevent", "-c", "8"] # Aumentado a 8 workers gevent
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          # ***** RECURSOS AUMENTADOS Y PROBES ELIMINADOS *****
          resources:
            requests:
              cpu: "1000m" # 1 CPU request (los workers necesitan más)
              memory: "2Gi" # 2 GiB request
            limits:
              cpu: "4000m" # 4 CPU limit (permitir uso intensivo)
              memory: "4Gi" # 4 GiB limit (aumentado significativamente)
            # --- Ejemplo para solicitar GPU (DESCOMENTAR Y AJUSTAR SI LA CONFIGURACIÓN LO PERMITE) ---
            # limits:
            #   nvidia.com/gpu: 1 # Solicitar 1 GPU NVIDIA
            # -----------------------------------------------------------------------------------
          # Se eliminan livenessProbe y readinessProbe según solicitud

      # imagePullSecrets: # Descomentar si usas registro privado
      # - name: your-registry-secret