# ingest-service/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker-deployment
  namespace: nyro-develop
  labels:
    app: ingest-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
    spec:
      # No se necesita serviceAccountName si usas claves
      containers:
        - name: ingest-worker
          # Ensure this image includes CPU ONNX runtime and correct dependencies
          # ACTUALIZA ESTA ETIQUETA con la imagen construida DESPUÉS de aplicar los cambios de código
          image: ghcr.io/dev-nyro/ingest-service:develop-e384ae5
          imagePullPolicy: Always
          command: ["celery"]
          args:
            [
              "-A",
              "app.tasks.celery_app",
              "worker",
              "--loglevel=INFO",
              "-P",
              "prefork",
              "-c",
              "4",
            ]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          env:
            # --- Establecer variable de entorno para la clave ---
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp-secrets/key.json" # Ruta donde se montará la clave
            # -------------------------------------------------
          volumeMounts:
            # --- Montar el secreto en el contenedor ---
            - name: gcp-key-volume
              mountPath: "/etc/gcp-secrets" # Directorio donde montar
              readOnly: true
            # ------------------------------------------
          resources:
            requests:
              cpu: "1000m"
              memory: "3Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
      volumes:
        # --- Definir el volumen desde el secreto ---
        - name: gcp-key-volume
          secret:
            secretName: gcs-worker-sa-key # Nombre del secreto creado
            items:
            - key: key.json # Nombre del archivo DENTRO del secreto
              path: key.json # Nombre que tendrá el archivo en mountPath
        # ---------------------------------------
      # imagePullSecrets:
      # - name: your-registry-secret
