# ingest-service/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker-deployment
  namespace: nyro-develop
  labels:
    app: ingest-worker
spec:
  replicas: 1 # Start with 1, scale if needed
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
    spec:
      # >>>>>>>>>>> CORRECTION: Add nodeSelector (adjust label as needed) <<<<<<<<<<<<<<
      # Example nodeSelector (adjust the label key/value to match your GPU nodes)
      nodeSelector:
        # Example: Select nodes specifically labeled for GPU tasks
        # nvidia.com/gpu.product: "NVIDIA-RTX-4060" # Adjust if using product label
        gpu-enabled: "true" # Or use a generic label you apply to GPU nodes
      # Example Tolerations (if GPU nodes have taints)
      # tolerations:
      # - key: "nvidia.com/gpu"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # >>>>>>>>>>> END CORRECTION <<<<<<<<<<<<<<
      containers:
        - name: ingest-worker
          # Ensure this image includes the new dependencies (fastembed-haystack, onnxruntime-gpu)
          image: ghcr.io/dev-nyro/ingest-service:develop-525f06b
          imagePullPolicy: Always
          command: ["celery"]
          # Keep concurrency as optimized previously, GPU handles parallelism internally
          args: ["-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "-P", "gevent", "-c", "8"]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          resources:
            # Keep increased CPU/Memory requests/limits as GPU still needs CPU coordination
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              # >>>>>>>>>>> CORRECTION: Add GPU limit <<<<<<<<<<<<<<
              nvidia.com/gpu: 1 # Request 1 GPU from the node
              # >>>>>>>>>>> END CORRECTION <<<<<<<<<<<<<<
              cpu: "4000m"
              memory: "4Gi"
          # Probes remain removed as per previous instructions

      # imagePullSecrets: # Uncomment if needed
      # - name: your-registry-secret