# ingest-service/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker-deployment
  namespace: nyro-develop
  labels:
    app: ingest-worker
spec:
  replicas: 1 # Start with 1, scale if needed (consider HPA later)
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
      # annotations: # Optional: restart pods on config/secret change
      #   checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      #   checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }} # Assuming secret.yaml exists
    spec:
      # --- NO GPU Node Selector needed ---
      containers:
        - name: ingest-worker
          # Ensure this image includes CPU ONNX runtime and correct dependencies
          # ACTUALIZA ESTA ETIQUETA con la imagen construida DESPUÉS de aplicar los cambios de código
          image: ghcr.io/dev-nyro/ingest-service:develop-428ba98
          imagePullPolicy: Always
          command: ["celery"]
          args:
            [
              "-A",
              "app.tasks.celery_app", # Points to the Celery app instance in celery_app.py
              "worker",
              "--loglevel=INFO", # Set Celery log level
              "-P", # Concurrency Pool Type
              "prefork", # Use processes for better CPU-bound task handling (like embeddings)
              "-c", # Concurrency (Number of child worker processes)
              "4", # Adjust based on available CPU resources (e.g., match CPU limits/requests if possible)
            ]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          resources:
            # Adjusted resources for CPU-only prefork worker
            requests:
              cpu: "1000m" # Request 1 CPU core initially
              memory: "3Gi" # Request 3 GiB RAM (Embeddings can be memory intensive)
            limits:
              # --- REMOVED nvidia.com/gpu limit ---
              cpu: "4000m" # Limit to 4 CPU cores (Matches concurrency -c 4)
              memory: "8Gi" # Limit to 8 GiB RAM (Allow headroom for peak usage)

      # imagePullSecrets: # Uncomment if needed for private registry
      # - name: your-registry-secret