# ingest-service/deployment-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api-deployment
  namespace: nyro-develop # Asegúrate que es el namespace correcto
  labels:
    app: ingest-api
spec:
  replicas: 1 # O más si necesitas alta disponibilidad
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      containers:
        - name: ingest-api
          image: ghcr.io/dev-nyro/ingest-service:develop-a201498
          imagePullPolicy: Always # Or IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # Command to run the FastAPI app with Gunicorn
          command: ["gunicorn"]
          args: [
              "-k", "uvicorn.workers.UvicornWorker", # Worker asíncrono
              "-w", "4",                             # Número de workers (ajustar según CPU/memoria)
              "-b", "0.0.0.0:8000",                  # Bind a todas las interfaces en el puerto 8000
              "-t", "120",                           # Timeout del worker en segundos (incrementado de 30 a 120)
              "app.main:app"                         # Módulo y aplicación FastAPI
            ]
          envFrom:
            - configMapRef:
                name: ingest-service-config # Asegúrate que el nombre es correcto
            - secretRef:
                name: ingest-service-secrets # Asegúrate que el nombre es correcto
          resources: # Ajusta según tus necesidades y pruebas
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      # imagePullSecrets: # Descomentar si usas registro privado
      # - name: your-registry-secret