# ingest-service/deployment-worker.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-worker-deployment
  namespace: nyro-develop
  labels:
    app: ingest-worker
spec:
  replicas: 1 # Start with 1, scale if needed
  selector:
    matchLabels:
      app: ingest-worker
  template:
    metadata:
      labels:
        app: ingest-worker
      # annotations: # Opcional: reiniciar pods al cambiar config/secret
      #   checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      #   checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }} # Asumiendo que tienes un secret.yaml
    spec:
      # --- REMOVED GPU Specific sections ---
      # nodeSelector:
      #   gpu-enabled: "true"
      # tolerations:
      # - key: "nvidia.com/gpu"
      #   operator: "Exists"
      #   effect: "NoSchedule"
      # --- END REMOVED GPU Specific sections ---
      containers:
        - name: ingest-worker
          # Ensure this image includes the CPU ONNX runtime and correct dependencies
          # ACTUALIZA ESTA ETIQUETA con la nueva imagen construida después de los cambios
          image: ghcr.io/dev-nyro/ingest-service:develop-XXXXXXX
          imagePullPolicy: Always
          command: ["celery"]
          # Args sin cambios, la concurrencia es para I/O con gevent, no CPU bound ahora
          args: ["-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "-P", "gevent", "-c", "8"]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          resources:
            # Ajusta los recursos para CPU-bound tasks si es necesario
            # FastEmbed puede consumir bastante CPU y RAM
            requests:
              cpu: "1000m" # 1 CPU core request
              memory: "2Gi" # 2 GiB RAM request
            limits:
              # --- REMOVED GPU limit ---
              # nvidia.com/gpu: 1
              # --- END REMOVED GPU limit ---
              cpu: "4000m" # Limit to 4 CPU cores
              memory: "6Gi"  # Aumentar límite de RAM para FastEmbed

      # imagePullSecrets: # Uncomment if needed
      # - name: your-registry-secret