# ingest-service/deployment-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-api-deployment
  namespace: nyro-develop
  labels:
    app: ingest-api
spec:
  replicas: 1 # Puedes aumentar si la API recibe muchas peticiones simultáneas
  selector:
    matchLabels:
      app: ingest-api
  template:
    metadata:
      labels:
        app: ingest-api
    spec:
      containers:
        - name: ingest-api
          # Asegúrate que la imagen es la correcta y está actualizada
          image: ghcr.io/dev-nyro/ingest-service:develop-5ae4b1a
          imagePullPolicy: Always # O IfNotPresent
          ports:
            - name: http
              containerPort: 8000 # Puerto que expone Gunicorn/Uvicorn
              protocol: TCP
          command: ["gunicorn"]
          args: [
              "-k", "uvicorn.workers.UvicornWorker",
              "-w", "4",                             # Número de workers (ajustar según CPU/memoria disponible)
              "-b", "0.0.0.0:8000",
              "-t", "120",                           # Timeout extendido
              "--log-level", "info",                 # Nivel de log para Gunicorn/Uvicorn
              "app.main:app"
            ]
          envFrom:
            - configMapRef:
                name: ingest-service-config
            - secretRef:
                name: ingest-service-secrets
          # ***** RECURSOS AUMENTADOS Y PROBES ELIMINADOS *****
          resources:
            requests:
              cpu: "250m"  # Un poco más de request base
              memory: "512Mi"
            limits:
              cpu: "1500m" # Permitir picos de CPU
              memory: "2Gi"  # Límite de RAM aumentado a 2 GiB
          # Se eliminan livenessProbe y readinessProbe según solicitud
      # imagePullSecrets: # Descomentar si usas registro privado
      # - name: your-registry-secret