apiVersion: v1
kind: Secret
metadata:
  name: ingest-service-secrets
  namespace: ingest-system
type: Opaque
data:
  # Use INGEST_ prefix consistent with config.py
  INGEST_POSTGRES_PASSWORD: "YOUR_BASE64_ENCODED_POSTGRES_PASSWORD" # e.g., cGFzc3dvcmQ=
  INGEST_OPENAI_API_KEY: "YOUR_BASE64_ENCODED_OPENAI_API_KEY"       # e.g., c2stYWJjZGVm...
  INGEST_MINIO_ACCESS_KEY: "YOUR_BASE64_ENCODED_MINIO_ACCESS_KEY"   # e.g., bWluaW9hZG1pbg== (for 'minioadmin')
  INGEST_MINIO_SECRET_KEY: "YOUR_BASE64_ENCODED_MINIO_SECRET_KEY"   # e.g., bWluaW9hZG1pbg== (for 'minioadmin')